; Listing generated by Microsoft (R) Optimizing Compiler Version 19.29.30037.0 

	TITLE	D:\C++_Learn\HelloWorld\HelloWorld\Debug\Math.obj
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

END
